dia = input('Dia =')
mes = input('Mes =')
ano = input('Ano =')
print('Você nasceu no dia', dia, 'de', mes, 'de', ano, '. Correto')
print('Você nasceu no dia', dia, 'de', mes, 'de', ano+'.','Correto')
