print('Aloha primo tudo bem???')
print('Esapero que sim ta bom')
nome = input('Mas ja que você esta aquiu então que tal agente converssar um pouco... pode me falar seu nome??? ')
idade = input('Oiiii {}, uuuuuu {}!!! que nome bonito uhum hum, então {} qual é sua idade??? '.format(nome, nome, nome))
print('Hey {} eu ainda não tenho {} anos, mas sou muito bom em matematica olha só ' .format(nome, idade))
n1 = int(input('Fala pra mim um numero uhum uhum '))
n2 = int(input('Ta {}, fala outro numero uhum uhum ' .format(n1)))
print('queeee essa é muito facil uhum uhum')
r = n1+n2
print('O resutado é {} uhum uhum' .format(r))
print('Eae que que acho??')
